let x = Boolean(1)
let y = Boolean(0)
let z = Boolean(5)
let p = Boolean("")
let q = Boolean(" ")
let r = Boolean([1,"hello"])
let a = Boolean("hello")
let b = Boolean(undefined)
let c = Boolean(NaN)
let i = Boolean(null)
let j = Boolean([])
let k = Boolean([0])

console.table([x,y,z,p,q,r,a,b,c,i,j,k])
console.table([typeof x, typeof y, typeof z,  typeof p, typeof q, typeof r, typeof a, typeof b, typeof c, typeof i, typeof j, typeof k])